# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: w:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/alarm_clock.srcs/sources_1/ip/bram_hey/bram_hey.xci
# IP: The module: 'bram_hey' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/alarm_clock.srcs/sources_1/ip/bram_hey/bram_hey_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_hey'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: w:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/alarm_clock.srcs/sources_1/ip/bram_hey/bram_hey.xci
# IP: The module: 'bram_hey' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/alarm_clock.srcs/sources_1/ip/bram_hey/bram_hey_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_hey'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
