# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: W:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/alarm_clock.srcs/sources_1/ip/bram_dreams/bram_dreams.xci
# IP: The module: 'bram_dreams' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/alarm_clock.srcs/sources_1/ip/bram_dreams/bram_dreams_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_dreams'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: W:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/alarm_clock.srcs/sources_1/ip/bram_dreams/bram_dreams.xci
# IP: The module: 'bram_dreams' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/alarm_clock.srcs/sources_1/ip/bram_dreams/bram_dreams_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_dreams'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
