@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Dec 10 23:18:15 -0500 2018
REM SW Build 2288692 on Thu Jul 26 18:24:02 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim timer_tb_behav -key {Behavioral:sim_1:Functional:timer_tb} -tclbatch timer_tb.tcl -view W:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/tob_tb_behav.wcfg -view W:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/audio_tb.wcfg -view W:/win/ELEC3500/lab/lab_9/fpga_alarm_clock/alarm_clock/timer_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
